---

- name: Load the facts
  set_fact:
    home_folder: '{{ lookup("env", "HOME") }}'
    gpg_folder: '{{ lookup("env", "HOME") }}/.gnupg'
    export_folder: '{{ backup_dir }}/{{ gnupg.name }}'
  tags: facts
