---

- name: Create the backup directory for this key
  file:
    path: '{{ backup_dir }}/{{ gnupg.name }}/'
    state: directory
  tags: gpgconf

- name: Deploy GPG configuration
  template:
    src: gpg.conf
    dest: '{{ gpg_folder }}/gpg.conf'
  tags: gpgconf
