---

- name: Get a random word for the acrostic
  register: random_word_cmd
  shell: >-
    xkcdpass
    --min {{ gnupg.passphrase.words.count }}
    --max {{ gnupg.passphrase.words.count }}
    --numwords 1
  changed_when: false

- name: Save the acrostic
  copy:
    content: '{{ random_word_cmd.stdout }}'
    dest: '{{ backup_dir }}/{{ gnupg.name }}/private/certify-key-acrostic'

- name: Generate a random pass phrase
  shell: >-
    xkcdpass --acrostic {{ random_word_cmd.stdout }}
    --min {{ gnupg.passphrase.words.min_length }}
    --max {{ gnupg.passphrase.words.max_length }}
    > {{ backup_dir }}/{{ gnupg.name }}/private/certify-key-passphrase
  args:
    creates: '{{ backup_dir }}/{{ gnupg.name }}/private/certify-key-passphrase'
  tags: passphrase

- name: Load the certify-key passphrase
  set_fact:
    certify_pass: >-
      {{ lookup("password", backup_dir + "/" + gnupg.name
      + "/private/certify-key-passphrase") }}
  tags: passphrase,facts
