---

- name: Install the required packages locally
  when: run_sudo_tasks
  include_tasks:
    file: packages.yml
  tags: apt

- name: Load the facts
  include_tasks:
    file: facts.yml
  tags: facts

- name: Reset the yubikey
  when: reset_key
  include_tasks:
    file: reset-key.yml
  tags: reset

- name: Set pin and security options
  include_tasks:
    file: security.yml
  tags: security

- name: Backup GnuPG folder configuration
  include_tasks:
    file: backup.yml
  tags: backup

- name: Transfer the keys on the Yubikey
  include_tasks:
    file: transfer.yml
  tags: transfer
