---

- name: Create the backup directory for this key
  file:
    path: '{{ backup_dir }}/{{ gnupg.name }}/'
    state: directory

- name: Create the GPG configuration directory
  file:
    path: '{{ gpg_folder }}'
    state: directory
    mode: '0700'

- name: Deploy GPG configuration
  template:
    src: gpg.conf
    dest: '{{ gpg_folder }}/gpg.conf'

- name: Kill any running agent
  shell: gpgconf --kill all

- name: Kill any running agent
  shell: gpgconf --launch all
