---

- name: Set the home folder
  set_fact:
    home_folder: '{{ lookup("env", "HOME") }}'

- name: Create the gnupg folder
  file:
    path: '{{ home_folder }}/.gnupg-{{ gnupg.name }}'
    state: directory
    mode: '0700'
  tags: files
