---

- name: Destroy the generated GPG key
  hosts: localhost
  vars:
    backup_dir: '{{ playbook_dir }}/../backup/'
  vars_files:
    - '{{ playbook_dir }}/../config/settings.yml'
  become: false
  roles:
    - name: Destroy the generated key
      role: destroy-key
      tags: gpg-key
