---

- name: Generte a PDF document to print with the key details
  hosts: localhost
  vars:
    backup_dir: '{{ playbook_dir }}/../backup'
  vars_files:
    - '{{ playbook_dir }}/../config/settings.yml'
  become: false
  roles:
    - name: Create a PDF document to print
      role: print-backup
      tags: print-backup
