---

- name: Backup the keys on an external drive
  hosts: localhost
  vars:
    backup_dir: '{{ playbook_dir }}/../backup'
    user: '{{ lookup("env", "USER") }}'
    home: '{{ lookup("env", "HOME") }}'
  vars_files:
    - '{{ playbook_dir }}/../config/settings.yml'
  roles:
    - name: Transfer the keys on a Yubikey
      role: transfer-yubikey
