---

- name: Backup the keys on a Yubikey
  hosts: localhost
  vars:
    backup_dir: '{{ playbook_dir }}/../backup'
    user: '{{ lookup("env", "USER") }}'
    home: '{{ lookup("env", "HOME") }}'
    run_sudo_tasks: false
  vars_files:
    - '{{ playbook_dir }}/../config/settings.yml'
  environment:
    GNUPGHOME: '{{ lookup("env", "HOME") }}/.gnupg-{{ gnupg.name }}'
  roles:
    - name: Transfer the keys on a Yubikey
      role: transfer-yubikey
