---

- name: Generate a random pass phrase
  shell: >-
    {{ passprase.gen_command }}
    > {{ backup_dir }}/{{ gnupg.name }}/luks-passphrase
  args:
    creates: '{{ backup_dir }}/{{ gnupg.name }}/luks-passphrase'

- name: Load the luks passphrase
  set_fact:
    luks_passphrase: >-
      {{ lookup("password", backup_dir + "/" + gnupg.name
      + "/luks-passphrase") }}
